# Generated by Django 3.1 on 2020-08-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tarefa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativa')),
            ],
        ),
    ]
